version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    networks:
      - nt2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 3s
      timeout: 10s
      retries: 30
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: mysqldb

  data-app:
    build: ./EnterDataApp
    networks:
      - nt2
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/students",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "123456",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    container_name: EnterDataApp

  authentication-app:
    build: ./authentication
    networks:
      - nt2
    ports:
      - "7070:7070"
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port" : "7070"
      }'
    container_name: AuthenticationApp

  analytics-app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./analytics
    networks:
      - nt2
    ports:
      - "6060:6060"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/students",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "123456",
              "spring.jpa.hibernate.ddl-auto" : "update",
              "server.port" : "6060"
            }'
    container_name: AnalyticsApp

  show-app:
    depends_on:
      analytics-app:
        condition: service_started
    build: ./showApp
    networks:
      - nt2
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/students",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "123456",
              "spring.jpa.hibernate.ddl-auto" : "update",
              "server.port" : "9090"
            }'
    container_name: ShowApp

networks:
  nt2: